# Generated by Django 5.2.9 on 2025-12-28 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_author_alter_product_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='disc',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
    ]
